Control/Lens/Plated.hs: amend for ghc-7.10
Build fails thusly (ghc-7.10.1_rc2/gcc-4.8.4):
    Building lens-4.8...
    Preprocessing library lens-4.8...

    src/Control/Lens/Plated.hs:716:0:
         error: detected recursion whilst expanding macro "OVERLAPPING"
         instance OVERLAPPING GPlated a (K1 i a) where
         ^

The reason is recursive macro definition:
    #define OVERLAPPING {-# OVERLAPPING #-}

Fixed by naming thing on the left differently.

Signed-off-by: Sergei Trofimovich <siarheit@google.com>